version: 0.0
os: linux
files:
  - source: /
    destination: /home/bitnami/apps/wordpress/htdocs/wp-content/themes/burgsviksbryggeri-theme
permissions:
   - object: /home/bitnami/apps/wordpress/htdocs/wp-content/themes/burgsviksbryggeri-theme
     pattern: "**"
